/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/tags/{tagId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 태그 단일 조회
     * @description 특정 태그를 조회합니다.
     */
    get: operations['getTag']
    /**
     * 태그 수정
     * @description 태그를 수정합니다.
     */
    put: operations['updateTag']
    post?: never
    /**
     * 태그 삭제
     * @description 태그를 삭제합니다.
     */
    delete: operations['deleteTag']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories/{categoryId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 카테고리 단일 조회
     * @description 특정 카테고리를 조회합니다.
     */
    get: operations['readCategory']
    /**
     * 카테고리 수정
     * @description 카테고리를 수정합니다. (관리자 전용)
     */
    put: operations['updateCategory']
    post?: never
    /**
     * 카테고리 삭제
     * @description 카테고리를 삭제합니다. (관리자 전용)
     */
    delete: operations['deleteCategory']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tags': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 전체 태그 조회
     * @description 모든 태그 목록을 조회합니다.
     */
    get: operations['getAllTags']
    put?: never
    /**
     * 태그 생성
     * @description 새로운 태그를 생성합니다.
     */
    post: operations['createTag']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/shorts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 숏폼 목록 조회
     * @description 숏폼 목록을 페이징하여 조회합니다. (스크롤링용: page=0&size=10)
     */
    get: operations['getShortsList']
    put?: never
    /**
     * 숏폼 업로드
     * @description 새로운 숏폼 영상을 업로드합니다. (로그인 필요)
     */
    post: operations['uploadShorts']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/files/videos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 비디오 업로드
     * @description 비디오 파일을 업로드합니다. (mp4, webm, mov 지원)
     */
    post: operations['uploadVideo']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/files/thumbnails': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 썸네일 업로드
     * @description 썸네일 이미지를 업로드합니다. (jpg, png, webp 지원)
     */
    post: operations['uploadThumbnail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 전체 카테고리 조회
     * @description 모든 카테고리 목록을 조회합니다.
     */
    get: operations['readAllCategories']
    put?: never
    /**
     * 카테고리 생성
     * @description 새로운 카테고리를 생성합니다. (관리자 전용)
     */
    post: operations['create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/signup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 회원가입
     * @description 새로운 사용자를 등록합니다.
     */
    post: operations['signup']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 토큰 재발급
     * @description Refresh Token으로 새로운 Access Token을 발급받습니다.
     */
    post: operations['refreshToken']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 로그아웃
     * @description 로그아웃합니다. (클라이언트에서 토큰 삭제)
     */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 로그인
     * @description 이메일과 비밀번호로 로그인합니다. Access Token과 Refresh Token을 반환합니다.
     */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/shorts/{shortId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 숏폼 상세 조회
     * @description 특정 숏폼을 포함한 페이징 데이터를 조회합니다. (page=0, size=20)
     */
    get: operations['getShortsDetails']
    put?: never
    post?: never
    /**
     * 숏폼 삭제
     * @description 숏폼을 삭제합니다. (본인 영상만 삭제 가능)
     */
    delete: operations['deleteShorts']
    options?: never
    head?: never
    /**
     * 숏폼 수정
     * @description 숏폼 정보를 수정합니다. (본인 영상만 수정 가능)
     */
    patch: operations['updateShorts']
    trace?: never
  }
  '/api/v1/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 전체 사용자 조회
     * @description 모든 사용자 목록을 조회합니다. (관리자용)
     */
    get: operations['getAllUsers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 사용자 조회
     * @description 특정 사용자 정보를 조회합니다.
     */
    get: operations['getUser']
    put?: never
    post?: never
    /**
     * 사용자 삭제
     * @description 사용자를 삭제합니다. (관리자용)
     */
    delete: operations['deleteUser']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 내 정보 조회
     * @description 로그인한 사용자의 정보를 조회합니다. (토큰 필요)
     */
    get: operations['getMyInfo']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/me/shorts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 내 숏폼 목록 조회
     * @description 로그인한 사용자가 업로드한 숏폼 목록을 조회합니다. (토큰 필요)
     */
    get: operations['getMyShorts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/stat': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 로그인 상태 조회
     * @description 현재 로그인 상태를 확인합니다. (토큰 필요)
     */
    get: operations['getAuthStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ApiResponseVoid: {
      success?: boolean
      message?: string
      data?: Record<string, never>
    }
    /** @description 태그 요청 */
    TagRequest: {
      /**
       * @description 태그 이름
       * @example Java
       */
      name: string
    }
    /** @description 태그 응답 */
    TagResponse: {
      /**
       * Format: int64
       * @description 태그 ID
       * @example 1
       */
      id?: number
      /**
       * @description 태그 이름
       * @example Java
       */
      name?: string
    }
    /** @description 카테고리 요청 */
    CategoryRequest: {
      /**
       * @description 카테고리 이름
       * @example 프로그래밍
       */
      name: string
    }
    /** @description 카테고리 응답 */
    CategoryResponse: {
      /**
       * Format: int64
       * @description 카테고리 ID
       * @example 1
       */
      id?: number
      /**
       * @description 카테고리 이름
       * @example 프로그래밍
       */
      name?: string
    }
    /** @description 숏폼 업로드 요청 */
    ShortsUploadRequest: {
      /**
       * Format: int64
       * @description 업로더 ID
       * @example 1
       */
      userId: number
      /**
       * Format: int64
       * @description 카테고리 ID
       * @example 1
       */
      categoryId: number
      /**
       * @description 영상 제목
       * @example Spring Boot 시작하기
       */
      title: string
      /**
       * @description 영상 설명
       * @example Spring Boot 입문자를 위한 가이드입니다.
       */
      description?: string
      /**
       * @description 영상 URL
       * @example /uploads/videos/abc123.mp4
       */
      videoUrl: string
      /**
       * @description 썸네일 URL
       * @example /uploads/thumbnails/abc123.jpg
       */
      thumbnailUrl?: string
      /**
       * Format: int32
       * @description 영상 길이(초)
       * @example 58
       */
      durationSec?: number
      /**
       * @description 태그 목록
       * @example [
       *       "Java",
       *       "Spring",
       *       "백엔드"
       *     ]
       */
      tagNames?: string[]
    }
    ApiResponseShortsResponse: {
      success?: boolean
      message?: string
      data?: components['schemas']['ShortsResponse']
    }
    /** @description 카테고리 정보 */
    CategoryDto: {
      /**
       * Format: int64
       * @description 카테고리 ID
       * @example 1
       */
      categoryId?: number
      /**
       * @description 카테고리 이름
       * @example 프로그래밍
       */
      name?: string
    }
    /** @description 숏폼 응답 */
    ShortsResponse: {
      /**
       * Format: int64
       * @description 숏폼 ID
       * @example 12
       */
      shortsId?: number
      /**
       * @description 제목
       * @example 스프링 DI 요약
       */
      title?: string
      /**
       * @description 설명
       * @example 1분 설명
       */
      description?: string
      /**
       * @description 영상 URL
       * @example https://cdn.xxx/v.mp4
       */
      videoUrl?: string
      /**
       * @description 썸네일 URL
       * @example https://cdn.xxx/t.png
       */
      thumbnailUrl?: string
      keywords?: string[]
      status?: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED'
      uploader?: components['schemas']['UploaderDto']
      category?: components['schemas']['CategoryDto']
    }
    /** @description 업로더 정보 */
    UploaderDto: {
      /**
       * Format: int64
       * @description 업로더 ID
       * @example 3
       */
      userId?: number
      /**
       * @description 업로더 닉네임
       * @example 코딩맨
       */
      nickname?: string
      /**
       * @description 프로필 URL
       * @example https://cdn.xxx/p.png
       */
      profileUrl?: string
    }
    /** @description 회원가입 요청 */
    UserSignUpRequest: {
      /**
       * @description 이메일
       * @example user@example.com
       */
      email?: string
      /**
       * @description 비밀번호 (8자 이상)
       * @example password123
       */
      password?: string
      /**
       * @description 이름
       * @example 홍길동
       */
      name?: string
    }
    /** @description 토큰 재발급 요청 */
    TokenRefreshRequest: {
      /**
       * @description 리프레시 토큰
       * @example eyJhbGciOiJIUzI1NiIs...
       */
      refreshToken: string
    }
    /** @description 로그인 응답 */
    UserLoginResponse: {
      /**
       * @description 액세스 토큰
       * @example eyJhbGciOiJIUzI1NiIs...
       */
      accessToken?: string
      /**
       * @description 리프레시 토큰
       * @example eyJhbGciOiJIUzI1NiIs...
       */
      refreshToken?: string
    }
    /** @description 로그인 요청 */
    UserLoginRequest: {
      /**
       * @description 이메일
       * @example user@example.com
       */
      email?: string
      /**
       * @description 비밀번호
       * @example password123
       */
      password: string
    }
    /** @description 숏폼 수정 요청 */
    ShortsUpdateRequest: {
      /**
       * @description 제목
       * @example 수정된 제목
       */
      title?: string
      /**
       * @description 설명
       * @example 수정된 설명
       */
      description?: string
      /**
       * Format: int64
       * @description 카테고리 ID
       * @example 2
       */
      categoryId?: number
      /**
       * @description 썸네일 URL
       * @example /uploads/thumbnails/new.jpg
       */
      thumbnailUrl?: string
      /**
       * Format: int32
       * @description 영상 길이(초)
       * @example 60
       */
      durationSec?: number
      /**
       * @description 공개 상태 (PUBLIC, PRIVATE)
       * @example PUBLIC
       * @enum {string}
       */
      status?: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED'
      /**
       * @description 태그 목록
       * @example [
       *       "React",
       *       "프론트엔드"
       *     ]
       */
      tagNames?: string[]
    }
    /** @description 사용자 응답 */
    UserResponse: {
      /**
       * Format: int64
       * @description 사용자 ID
       * @example 1
       */
      id?: number
      /**
       * @description 이메일 (본인만 조회 가능)
       * @example user@example.com
       */
      email?: string
      /**
       * @description 이름
       * @example 홍길동
       */
      name?: string
      /**
       * @description 닉네임
       * @example 길동이
       */
      nickname?: string
    }
    Pageable: {
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      sort?: string[]
    }
    PageShortsResponse: {
      /** Format: int32 */
      totalPages?: number
      /** Format: int64 */
      totalElements?: number
      first?: boolean
      last?: boolean
      /** Format: int32 */
      size?: number
      content?: components['schemas']['ShortsResponse'][]
      /** Format: int32 */
      number?: number
      sort?: components['schemas']['SortObject']
      /** Format: int32 */
      numberOfElements?: number
      pageable?: components['schemas']['PageableObject']
      empty?: boolean
    }
    PageableObject: {
      /** Format: int64 */
      offset?: number
      sort?: components['schemas']['SortObject']
      /** Format: int32 */
      pageNumber?: number
      /** Format: int32 */
      pageSize?: number
      paged?: boolean
      unpaged?: boolean
    }
    SortObject: {
      empty?: boolean
      sorted?: boolean
      unsorted?: boolean
    }
    ApiResponsePageShortsResponse: {
      success?: boolean
      message?: string
      data?: components['schemas']['PageShortsResponse']
    }
    /** @description 로그인 상태 응답 */
    AuthStatusResponse: {
      /**
       * @description 로그인 여부
       * @example true
       */
      isLoggedIn?: boolean
      /**
       * @description 이메일
       * @example user@example.com
       */
      email?: string
      /**
       * @description 이름
       * @example 홍길동
       */
      name?: string
      /**
       * @description 닉네임
       * @example 길동이
       */
      nickname?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getTag: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description 태그 ID
         * @example 1
         */
        tagId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TagResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  updateTag: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description 태그 ID
         * @example 1
         */
        tagId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TagRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TagResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  deleteTag: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description 태그 ID
         * @example 1
         */
        tagId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  readCategory: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description 카테고리 ID
         * @example 1
         */
        categoryId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CategoryResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description 카테고리를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  updateCategory: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description 카테고리 ID
         * @example 1
         */
        categoryId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CategoryResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  deleteCategory: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description 카테고리 ID
         * @example 1
         */
        categoryId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 삭제 성공 */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description 카테고리를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  getAllTags: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TagResponse'][]
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  createTag: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TagRequest']
      }
    }
    responses: {
      /** @description 생성 성공 */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TagResponse']
        }
      }
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  getShortsList: {
    parameters: {
      query: {
        /** @description 페이지 정보 (page, size, sort) */
        pageable: components['schemas']['Pageable']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageShortsResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  uploadShorts: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ShortsUploadRequest']
      }
    }
    responses: {
      /** @description 업로드 성공 */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseShortsResponse']
        }
      }
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  uploadVideo: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          /**
           * Format: binary
           * @description 비디오 파일 (mp4, webm, mov)
           */
          file: string
        }
      }
    }
    responses: {
      /** @description 업로드 성공 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': {
            [key: string]: string
          }
        }
      }
      /** @description 지원하지 않는 파일 형식 */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  uploadThumbnail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          /**
           * Format: binary
           * @description 썸네일 이미지 (jpg, png, webp)
           */
          file: string
        }
      }
    }
    responses: {
      /** @description 업로드 성공 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': {
            [key: string]: string
          }
        }
      }
      /** @description 지원하지 않는 파일 형식 */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  readAllCategories: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CategoryResponse'][]
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryRequest']
      }
    }
    responses: {
      /** @description 생성 성공 */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CategoryResponse']
        }
      }
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description 중복된 카테고리명 */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  signup: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserSignUpRequest']
      }
    }
    responses: {
      /** @description 회원가입 성공 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description 이미 존재하는 이메일 */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  refreshToken: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenRefreshRequest']
      }
    }
    responses: {
      /** @description 재발급 성공 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UserLoginResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description 유효하지 않은 Refresh Token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserLoginRequest']
      }
    }
    responses: {
      /** @description 로그인 성공 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UserLoginResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description 인증 실패 (이메일 또는 비밀번호 오류) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  getShortsDetails: {
    parameters: {
      query: {
        /** @description 페이지 정보 (기본: page=0, size=20) */
        pageable: components['schemas']['Pageable']
      }
      header?: never
      path: {
        /**
         * @description 숏폼 ID
         * @example 1
         */
        shortId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageShortsResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description 숏폼을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  deleteShorts: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description 숏폼 ID
         * @example 1
         */
        shortId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 삭제 성공 */
      204: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description 숏폼을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  updateShorts: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description 숏폼 ID
         * @example 1
         */
        shortId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ShortsUpdateRequest']
      }
    }
    responses: {
      /** @description 수정 성공 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseShortsResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description 숏폼을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  getAllUsers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UserResponse'][]
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  getUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description 사용자 ID
         * @example 1
         */
        userId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UserResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  deleteUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description 사용자 ID
         * @example 1
         */
        userId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  getMyInfo: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UserResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  getMyShorts: {
    parameters: {
      query: {
        /** @description 페이지 정보 */
        pageable: components['schemas']['Pageable']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PageShortsResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  getAuthStatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AuthStatusResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': {
            [key: string]: Record<string, never>
          }
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
}
